name: budget_tracker
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: 4.6.6
  intl: ^0.19.0



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
